"""`ckpt-chaos repro`: a standalone script and a draft issue for each failing crash point of a run.

The script rebuilds one crash point on its own: fault-free run, kill at the same file event, resume, verdict.
It uses the same judging rules and the same helpers as `ckpt-chaos run`, so it needs the same ckpt-chaos version.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from .invariants import ResumeOutcome, classify

ORDER = ["HARD_FAIL", "SILENT_DIVERGENCE", "LOST_WORK"]
REPEAT = 3
MEANING = {
    "HARD_FAIL": "the resume raised an error, so the job does not come back up on its own",
    "SILENT_DIVERGENCE": "the resume ran, but its result differs from an uninterrupted run",
    "LOST_WORK": "the resume started from an older checkpoint than the newest complete one, or from scratch",
}
MODE_TEXT = {
    "before": "the job is killed before the file is written",
    "torn": "the file is cut to half its size, then the job is killed",
    "term": "the job gets SIGTERM, and is killed if it is still running when the grace period ends",
}

TEMPLATE = '''#!/usr/bin/env python3
"""Reproduces one crash-recovery failure found by ckpt-chaos. Generated by `ckpt-chaos repro`.

Needs: pip install @@PIP@@ and whatever your training command needs.
Copy this file into your project root (the directory your command is relative to) and run it with the Python
your training uses (that interpreter also runs the job):

    python repro.py

It runs the job once without a fault, then interrupts a fresh copy at one file event (mode @@MODE_NAME@@: @@MODE_TEXT@@),
@@REPEAT@@ times, resumes it, and judges each resume with the same rules as `ckpt-chaos run`.
Exit code 1 if the failure reproduces. Set PROJECT_DIR to run it from somewhere else.
"""
import hashlib
import os
import re
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path

import ckpt_chaos
from ckpt_chaos.byo import _newest_complete, _snapshot
from ckpt_chaos.invariants import ResumeOutcome, classify

TRAIN = @@TRAIN@@
RESUME = @@RESUME@@
STEP_REGEX = @@STEP_REGEX@@
CHECKPOINT_GLOB = @@CHECKPOINT_GLOB@@
IGNORE_SIZE = @@IGNORE_SIZE@@
RESULT_FILE = @@RESULT_FILE@@
RESULT_CMD = @@RESULT_CMD@@
CRASH_AT = @@CRASH_AT@@  # the file event the job is interrupted at, numbered as in the original run
MODE = @@MODE@@  # before: killed before the write; torn: file cut to half, then killed; term: SIGTERM, killed after GRACE
GRACE = @@GRACE@@  # term mode: seconds between SIGTERM and the kill
EXPECT_EVENT = @@EVENT@@  # [kind, name] the job should be writing at that point
REPEAT = @@REPEAT@@
# "{python}" stands for the interpreter that runs this script, so the repro works on any machine
TRAIN = [sys.executable if a == "{python}" else a for a in TRAIN]
RESUME = [sys.executable if a == "{python}" else a for a in RESUME]
PROJECT = Path(os.environ.get("PROJECT_DIR", ".")).resolve()
BOOT = Path(ckpt_chaos.__file__).resolve().parent / "_boot"
PKG_PARENT = Path(ckpt_chaos.__file__).resolve().parent.parent


def env_for(extra=None):
    e = dict(os.environ, PYTHONIOENCODING="utf-8")
    e["PYTHONPATH"] = os.pathsep.join([str(BOOT), str(PKG_PARENT)] + ([os.environ["PYTHONPATH"]] if "PYTHONPATH" in os.environ else []))
    e.update(extra or {})
    return e


def armed(out, log, crash=None):
    extra = {"CKPT_CHAOS_WATCH": str(out), "CKPT_CHAOS_LOG": str(log), "CKPT_CHAOS_TORN_PYTHON": "1"}
    if crash is not None:
        extra.update(CKPT_CHAOS_CRASH_AT=str(crash), CKPT_CHAOS_MODE=MODE, CKPT_CHAOS_GRACE_S=str(GRACE))
    return env_for(extra)


def sub(args, out):
    return [a.replace("{out}", str(out)) for a in args]


def run(cmd, env, timeout=900):
    try:
        p = subprocess.run(cmd, env=env, cwd=PROJECT, capture_output=True, text=True, encoding="utf-8",
                           errors="replace", timeout=timeout)
        return p.returncode, (p.stdout or "") + (p.stderr or "")
    except subprocess.TimeoutExpired:
        return -9, "TIMEOUT"


def fingerprint(out):
    if RESULT_FILE:
        p = Path(RESULT_FILE.replace("{out}", str(out)))
        return hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else "MISSING"
    if RESULT_CMD:
        rc, text = run(shlex.split(RESULT_CMD.replace("{out}", str(out)), posix=os.name != "nt"), env_for())  # as the harness
        return text.strip() if rc == 0 else f"ERROR({rc})"
    return None


def events(log):
    p = log.with_name(log.name + ".rank0")
    rows = []
    if p.exists() and p.stat().st_size:
        for line in p.read_text(encoding="utf-8").strip().splitlines():
            n, kind, name, _ = line.split("\\t")
            rows.append((int(n), kind, name))
    return rows


def attempt(work, ref_fp, ref_ckpts):
    work.mkdir(parents=True, exist_ok=True)  # the injector opens its event log here before the job starts
    out = work / "out"
    log = work / "events.log"
    rc, _ = run(sub(TRAIN, out), armed(out, log, CRASH_AT))
    if rc == 0 and MODE != "term":  # after a SIGTERM a job may exit 0 on its own; that resume is still judged
        return "NO_CRASH", f"the job finished without reaching file event {CRASH_AT}"
    seen = events(log)
    drift = not any(e[0] == CRASH_AT and [e[1], e[2]] == EXPECT_EVENT for e in seen)
    newest = _newest_complete(ref_ckpts, _snapshot(CHECKPOINT_GLOB, out), IGNORE_SIZE) if CHECKPOINT_GLOB else 0
    rrc, rtext = run(sub(RESUME, out), env_for())
    raised = None if rrc == 0 else ("Timeout" if rtext == "TIMEOUT" else f"ExitCode{rrc}")
    step = None
    if STEP_REGEX and raised is None:
        m = re.search(STEP_REGEX, rtext)
        step = int(m.group(1)) if m else None
    diff = None
    if raised is None:
        got = fingerprint(out)
        diff = 0.0 if ref_fp is None or got == ref_fp else 1.0
    verdict = classify(ResumeOutcome(raised, step, newest, diff))
    if raised:
        detail = f"RAISED {raised}"
    else:
        detail = f"resumed from step {step}, newest complete checkpoint {newest}, result {'matches' if diff == 0.0 else 'DIFFERS'}"
    if drift:
        detail += "  [the job wrote different file events than the original run]"
    return verdict, detail


def main():
    work = Path(tempfile.mkdtemp(prefix="ckpt-chaos-repro-"))
    ref = work / "reference" / "out"
    rc, text = run(sub(TRAIN, ref), env_for())
    if rc != 0:
        sys.exit(f"the job fails without any fault (exit {rc}), so there is nothing to reproduce yet:\\n{text[-1500:]}")
    ref_fp = fingerprint(ref)
    ref_ckpts = _snapshot(CHECKPOINT_GLOB, ref) if CHECKPOINT_GLOB else {}
    print(f"fault-free run ok. Killing the job at file event {CRASH_AT} ({EXPECT_EVENT[0]} {EXPECT_EVENT[1]}, {MODE}) "
          f"{REPEAT} times")
    reproduced = 0
    for i in range(1, REPEAT + 1):
        verdict, detail = attempt(work / f"attempt{i}", ref_fp, ref_ckpts)
        print(f"attempt {i}: {verdict}: {detail}")
        reproduced += verdict in ("HARD_FAIL", "SILENT_DIVERGENCE", "LOST_WORK")
    print(f"reproduced {reproduced} of {REPEAT}")
    return 1 if reproduced else 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _records(run_dir: Path) -> list[dict]:
    return sorted((json.loads(p.read_text(encoding="utf-8")) for p in run_dir.glob("pt_*/result.json")),
                  key=lambda r: r["order"])


def select(run_dir: Path, limit: int) -> list[tuple[str, dict]]:
    """Failing crash points, taking one of each verdict in turn so that a small limit still shows every kind."""
    groups: dict[str, list] = {v: [] for v in ORDER}
    for rec in _records(run_dir):
        if rec.get("point") is None:
            continue  # the fault-free control has no crash point
        verdict = classify(ResumeOutcome(**rec["outcome"]))
        if verdict in groups:
            groups[verdict].append((verdict, rec))
    picked: list[tuple[str, dict]] = []
    while len(picked) < limit and any(groups.values()):
        for v in ORDER:
            if groups[v] and len(picked) < limit:
                picked.append(groups[v].pop(0))
    return picked


def _path_forms(p: str) -> list[str]:
    """A path as it appears in text: plain, with doubled backslashes (a Python repr), and with forward slashes."""
    forms = {p, p.replace("\\", "\\\\"), p.replace("\\", "/")}
    return sorted(forms, key=len, reverse=True)  # longest first, so a shorter prefix cannot hide a longer match


def _scrub(text: str, meta: dict) -> str:
    """Keep local paths out of text that is going to a public issue."""
    if meta.get("work"):
        for form in _path_forms(meta["work"]):
            text = text.replace(form, "<work>")
    for form in _path_forms(str(Path.home())):
        text = text.replace(form, "~")
    return text


_PYTHON = re.compile(r"^python(\d+(\.\d+)?)?(\.exe)?$", re.IGNORECASE)


def _portable(args: list[str], meta: dict) -> list[str]:
    """The job's command, runnable on another machine and free of local paths: the interpreter becomes "{python}"
    (repro.py puts in the one it runs under), paths inside the project become relative, the home folder becomes ~."""
    cwd = meta.get("cwd")
    out = []
    for i, a in enumerate(args):
        p = Path(a)
        if i == 0 and _PYTHON.match(p.name):
            out.append("{python}")
            continue
        if cwd and p.is_absolute():
            try:
                out.append(p.relative_to(cwd).as_posix())
                continue
            except ValueError:
                pass
        out.append(_scrub(a, meta))
    return out


def _pip(meta: dict) -> str:
    v = meta.get("versions", {}).get("ckpt-chaos")
    return f"ckpt-chaos=={v}" if v else "ckpt-chaos"


def script(meta: dict, rec: dict) -> str:
    n, mode = rec["point"]
    kind, name = rec["event"]
    scrubbed = {k: (_scrub(meta[k], meta) if meta.get(k) else None) for k in ("result_file", "result_cmd")}
    values = {
        "@@PIP@@": _pip(meta),
        "@@MODE_NAME@@": mode,
        "@@MODE_TEXT@@": MODE_TEXT.get(mode, mode),
        "@@TRAIN@@": repr(_portable(meta["train"], meta)),
        "@@RESUME@@": repr(_portable(meta["resume"], meta)),
        "@@STEP_REGEX@@": repr(meta.get("step_regex")),
        "@@CHECKPOINT_GLOB@@": repr(meta.get("checkpoint_glob")),
        "@@IGNORE_SIZE@@": repr(bool(meta.get("ignore_size"))),
        "@@RESULT_FILE@@": repr(scrubbed["result_file"]),
        "@@RESULT_CMD@@": repr(scrubbed["result_cmd"]),
        "@@CRASH_AT@@": str(n),
        "@@MODE@@": repr(mode),
        "@@GRACE@@": repr(float(meta.get("grace", 5.0))),
        "@@EVENT@@": repr([kind, name]),
        "@@REPEAT@@": str(REPEAT),
    }
    text = TEMPLATE
    for token, value in values.items():
        text = text.replace(token, value)
    return text


def issue(meta: dict, rec: dict, verdict: str) -> str:
    n, mode = rec["point"]
    kind, name = rec["event"]
    o = rec["outcome"]
    ver = meta["versions"]
    if o["raised"]:
        observed = f"The resume raised `{o['raised']}`."
    elif verdict == "SILENT_DIVERGENCE":
        observed = "The resume finished, but its result differs from an uninterrupted run."
    else:
        observed = (f"The resume started from step {o['resumed_from_step']}, but the newest complete checkpoint "
                    f"was step {o['newest_complete_step']}.")
    steps = meta.get("reference_steps")
    checkpoints = (f"The fault-free run wrote checkpoints at steps {', '.join(map(str, steps))}."
                   if steps else "Checkpoint steps were not tracked for this run.")
    setup = [f"- ckpt-chaos {ver.get('ckpt-chaos', 'unknown')}", f"- Python {ver['python']} on {ver['platform']}"]
    setup += [f"- {k} {v}" for k, v in ver.items() if k not in ("python", "platform", "ckpt-chaos")]
    tail = _scrub(rec.get("resume_tail", ""), meta).strip().splitlines()[-20:]
    what = "a SIGTERM (preemption)" if mode == "term" else "a kill"
    lines = [
        f"# Resume after {what} during checkpoint save: {verdict}",
        "",
        f"Interrupting the job at file event #{n} (`{kind}` on `{name}`, mode {mode}: {MODE_TEXT.get(mode, mode)}) "
        f"during a checkpoint save, then resuming it, gives **{verdict}**: {MEANING[verdict]}.",
        "",
        "## Expected",
        "",
        f"After {what} at any file event of a checkpoint save, the resume should continue from the newest complete "
        "checkpoint and reach the same result as an uninterrupted run.",
        "",
        "## Observed",
        "",
        observed,
        "",
        checkpoints,
        "",
        "## Setup",
        "",
        *setup,
        "",
        "## Reproduce",
        "",
        f"Copy `repro.py` into the project root and run it. It repeats the crash {REPEAT} times.",
        "",
        "```bash",
        f"pip install {_pip(meta)}",
        "python repro.py",
        "```",
        "",
        "Output of `python repro.py` (paste it here before filing):",
        "",
        "```",
        "<paste>",
        "```",
        "",
        "## Resume output (last lines of the original run)",
        "",
        "```",
        *tail,
        "```",
    ]
    return "\n".join(lines) + "\n"


def write(run_dir: Path, dest: Path, limit: int = 3) -> list[Path]:
    meta_file = run_dir / "meta.json"
    if not meta_file.exists():
        raise SystemExit(f"{run_dir} has no meta.json, so it was made by an older ckpt-chaos. Run the job again to make one.")
    meta = json.loads(meta_file.read_text(encoding="utf-8"))
    written = []
    for verdict, rec in select(run_dir, limit):
        n, mode = rec["point"]
        d = dest / f"{verdict.lower()}-{n:03d}-{mode}"
        d.mkdir(parents=True, exist_ok=True)
        (d / "repro.py").write_text(script(meta, rec), encoding="utf-8")
        (d / "ISSUE.md").write_text(issue(meta, rec, verdict), encoding="utf-8")
        written.append(d)
    return written
